# Generated by Django 4.2.7 on 2023-12-01 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_quote_author_remove_quote_user_delete_author_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
